image: "debian:bullseye-slim"

before_script:
  - apt-get update -y
  - apt-get install -y make python3-pip python3-venv python3-yaml texlive-metapost libharfbuzz-bin
  - pip3 install -r requirements.txt

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - make build release
  artifacts:
    paths:
    - fonts/
  except:
    - tags

test:
  stage: test
  allow_failure: true
  script:
    - make test

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -rf fonts tests public
  artifacts:
    paths:
      - public  # instruct GitLab to keep the public folder
  only:
    - master

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  before_script:
    - echo "Pass. Just overriding"
  script:
    - echo "Running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG of $CI_PROJECT_NAME'
    description: 'Rlease $CI_COMMIT_TAG' # Need to replace with 'CHANGELOG.md'
    # tag_name is a mandatory field and can not be an empty string
    tag_name: '$CI_COMMIT_TAG'
    ref: $CI_COMMIT_TAG
    assets:
      links:
        - name: 'Nupuram Variable font - Nupuram-VF.ttf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-VF.ttf'
        - name: 'Nupuram Variable font - Nupuram-VF.otf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/otf/Nupuram-VF.otf'
        - name: 'Nupuram Calligraphy variable font - Nupuram-Calligraphy-VF.ttf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-Calligraphy-VF.ttf'
        - name: 'Nupuram Calligraphy Variable font - Nupuram-Calligraphy-VF.otf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/otf/Nupuram-Calligraphy-VF.otf'
        - name: 'Nupuram Color font - Nupuram-Color-v0.ttf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-Color-v0.ttf'
        - name: 'Nupuram Color font - Nupuram-Color-v1.ttf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-Color-v1.ttf'
        - name: 'Nupuram Color font - Nupuram-Color-v0.otf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/otf/Nupuram-Color-v0.otf'
        - name: 'Nupuram Color font - Nupuram-Color-v1.otf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/otf/Nupuram-Color-v1.otf'
        - name: 'Nupuram Arrows Color font ColrV0 - Nupuram-Arrows-Color-v0.ttf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-Arrows-Color-v0.ttf'
        - name: 'Nupuram Arrows Color font ColrV0 - Nupuram-Arrows-Color-v0.otf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/otf/Nupuram-Arrows-Color-v0.otf'
        - name: 'Nupuram Arrows Color font ColrV1 - Nupuram-Arrows-Color-v1.ttf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-Arrows-Color-v1.ttf'
        - name: 'Nupuram Arrows Color font ColrV1 - Nupuram-Arrows-Color-v1.otf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/otf/Nupuram-Arrows-Color-v1.otf'
        - name: 'Nupuram Dots font - Nupuram-Dots.ttf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-Dots.ttf'
        - name: 'Nupuram Dots font - Nupuram-Dots.otf'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/otf/Nupuram-Dots.otf'
        - name: 'TTF, OTF, Webfonts fonts - Nupuram.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram.zip'
        - name: 'TTF, OTF, Webfonts fonts - Nupuram.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram.tar.gz'
        - name: 'Webfonts fonts - Nupuram-webfonts.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-webfonts.zip'
        - name: 'TTF, OTF, Webfonts fonts - Nupuram.webfonts.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram.webfonts.tar.gz'
        - name: 'Font source in UFO format - Nupuram-ufo.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-ufo.zip'
        - name: 'Font source in UFO format - Nupuram.ufo.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram.ufo.tar.gz'

