image: "debian:bullseye-slim"

before_script:
  - apt-get update -y
  - apt-get install -y make python3-pip python3-venv python3-yaml texlive-metapost libharfbuzz-bin
  - pip3 install -r requirements.txt

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - make build release
  artifacts:
    expire_in: 1000 yrs
    paths:
    - fonts/

test:
  stage: test
  script:
    - make test

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -rf fonts tests public
  artifacts:
    expire_in: 1000 yrs
    paths:
      - public  # instruct GitLab to keep the public folder
  only:
    - master

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  before_script:
    - echo "Pass. Just overriding"
  script:
    - echo "Running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG of $CI_PROJECT_NAME'
    description: 'Release $CI_COMMIT_TAG' # Need to replace with 'CHANGELOG.md'
    # tag_name is a mandatory field and can not be an empty string
    tag_name: '$CI_COMMIT_TAG'
    ref: $CI_COMMIT_TAG
    assets:
      links:
        - name: 'Nupuram Variable font - Nupuram.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram.tar.gz'
        - name: 'Nupuram Variable font - Nupuram.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram.zip'
        - name: 'Nupuram Calligraphy Variable font - Nupuram-Calligraphy.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Calligraphy.tar.gz'
        - name: 'Nupuram Calligraphy Variable font - Nupuram-Calligraphy.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Calligraphy.zip'
        - name: 'Nupuram Color font - Nupuram-Color.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/ttf/Nupuram-Color.tar.gz'
        - name: 'Nupuram Color font - Nupuram-Color.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Color.zip'
        - name: 'Nupuram Arrows Color font - Nupuram-Arrows-Color.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Arrows-Color.tar.gz'
        - name: 'Nupuram Arrows Color font - Nupuram-Arrows-Color.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Arrows-Color.zip'
        - name: 'Nupuram Dots font - Nupuram-Dots.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Dots.tar.gz'
        - name: 'Nupuram Dots font - Nupuram-Dots.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Dots.zip'
        - name: 'Nupuram Display font - Nupuram-Display.tar.gz'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Display.tar.gz'
        - name: 'Nupuram Display font - Nupuram-Display.zip'
          url: 'https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Display.zip'
