image: "registry.gitlab.com/smc/dockerfiles:font-builder"

stages:
  - build
  - test
  - deploy

build-branch:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip python3-venv python3-yaml fontforge python3-fontforge
    - pip3 install -r requirements.txt
  script:
    - make build
  artifacts:
    paths:
    - fonts/
  except:
    - tags

test:
  stage: test
  allow_failure: true
  before_script:
    - apt-get update -y
    - apt-get install -y make libharfbuzz-bin python3-pip python3-venv python3-yaml fontforge python3-fontforge
    - pip3 install -r requirements.txt
  script:
    - make test

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -rf fonts proofs tests public
  artifacts:
    paths:
      - public  # instruct GitLab to keep the public folder
  only:
    - master

