image: "debian:bullseye-slim"

before_script:
  - apt-get update -y
  - apt-get install -y make python3-pip python3-venv python3-yaml texlive-metapost libharfbuzz-bin
  - pip3 install -r requirements.txt

stages:
  - build
  - test
  - deploy
  - release

build-branch:
  stage: build
  script:
    - make build
  artifacts:
    paths:
    - fonts/
  except:
    - tags

test:
  stage: test
  allow_failure: true
  script:
    - make test

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -rf fonts tests public
  artifacts:
    paths:
      - public  # instruct GitLab to keep the public folder
  only:
    - master

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  before_script:
    - echo "Overriding default before_script. Pass"
  script:
    - echo 'running release_job'
    - make build
  artifacts:
    paths:
    - fonts/
  release:
    name: 'Release $CI_COMMIT_SHORT_SHA of $CI_PROJECT_NAME'
    description: 'Created using the release-cli' # Need to replace with 'CHANGELOG.md'
    # tag_name is a mandatory field and can not be an empty string
    tag_name: '$CI_COMMIT_TAG'
    ref: $CI_COMMIT_TAG
    assets:
      links:
        - name: 'Binary fonts'
          url: 'https://gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/artifacts/$CI_COMMIT_TAG/download?job=release'
