name: Seventy
styles: ["Regular", "Outline", "Shadow", "Color"]
version: 1.0
source: https://gitlab.com/smc/fonts/seventy
author:
  name: Santhosh Thottingal
  email: santhosh.thottingal@gmail.com
  url: https://thottingal.in
license:
  test: "This Font Software is licensed under the SIL Open Font License, Version 1.1. This licens is available with a FAQ at: https://scripts.sil.org/OFL"
  url: https://scripts.sil.org/OFL
manufacturer:
  name: SMC
  url: https://smc.org.in
sources: sources
build: fonts
proofs: proofs
tests: tests
glyphs:
  classes:
    LC_ALL: abcdefghijklmnopqrstuvwxyz
    UC_ALL: ABCDEFGHIJKLMNOPQRSTUVWXYZ
    LATIN_EXTRA: ÁǼÂÄÀĀÅÃĆČÇĈĊĎÉĚÊËĖÈĒĜĠĤÍÎÏÌĪĨŃŇÑÓÔÖÒŌÕŔŘŚŠŞŜÚǓÛÜÙŪŮŨŴÝŶŽŻáǽâäàāåãćčçĉċéěêëėèēĝġĥíîïìīĩńňñóǒôöòōõŕřśšşŝúǔûüùūůũŵýŷÿźžż
    LATIN_LIGATURES:  ["ffi", "ff", "ee", "th", "ft", "fi", "tt"]
    LC_LEFT_ROUND: ["e", "ee", "c", "a", "d", "o", "q", "g"]
    LC_RIGHT_ROUND: bop
    UC_LEFT_ROUND: OQ
    UC_RIGHT_ROUND: OQDP
    UC_RIGHT_MOUTH: K
    LC_RIGHT_SLANT: ["v", "f", "ff", "k"]
    LC_LEFT_SLANT: ["v"]
    UC_LEFT_SLANT: ["A", "V", "Y", "T"]
    UC_RIGHT_SLANT: TY
    UC_RIGHT_LEG: ["L"]
    UC_RIGHT_ARM: ["T"]
    LC_RIGHT_ARM: rf
    UC_LEFT_LEG: ["J"]
    LC_LEFT_LEG: ["j"]
    LC_RIGHT_LEG: ["t"]
    LC_RIGHT_MOUTHS: amd
    LC_BOTTOM_GAP: abcdefhiklmnopqrstuvwxz
    QUOTES: ["'","\"","‘","’","“","”"]
    PARANTHESIS: "()"
    ML_CONSONANTS: കഖഗഘങചഛജഝഞടഠഡഢണതഥദധനപഫബഭമയരലവറശഷസഹളഴ
    ML_VOWEL_SIGNS: ['ാ', 'ി','ീ', "ു", "ൂ", "ൃ", "ൄ", "ൢ", "ൣ", "െ", "േ", "ൈ", "ൊ", "ോ","ൌ", "ൗ"]
    ML_VOWEL_SIGNS_CONJOINING: ["ു", "ൂ", "ൃ", "ൄ", "ൢ", "ൣ"]
    ML_I_SIGNS: ['ി','ീ']
    ML_CONS_CONJUNCTS: ["ക്ക", "ക്ഷ", "ഗ്ഗ", "ഗ്ദ", "ഗ്ദ്ധ", "ഗ്ന", "ഗ്മ", "ങ്ങ", "ക്ത", "ങ്ക",
                     "ച്ച", "ച്ഛ", "ജ്ജ", "ഞ്ച", "ഞ്ജ", "ജ്ഞ", "ഞ്ഞ",
                     "ട്ട", "ണ്ണ", "ണ്ഡ", "ണ്ട", "ണ്മ",
                     "ത്ത", "ത്ഥ", "ത്ന", "ത്ഭ", "ദ്ദ", "ദ്ധ", "ന്ന", "ത്സ", "ത്മ", "ന്ത", "ന്ഥ", "ന്ദ", "ന്ധ", "ന്മ", "ന്റ", "ൻ്റ",
                     "പ്പ", "പ്ഫ", "ബ്ബ", "മ്മ", "മ്പ",
                     "യ്യ", "ല്ല", "വ്വ",
                     "ശ്ച", "സ്സ", "സ്ഥ", "ശ്ശ", "ഷ്ട", "ഹ്ന", "ഹ്മ", "ള്ള", "റ്റ"]
    ML_REPH_CONJUNCTS: ["ക്ര", "ക്ക്ര", "ക്ത്ര", "ഗ്ര", "ഘ്ര", "ങ്ക്ര",
                     "ച്ര", "ജ്ര", "ട്ര", "ഡ്ര", "ഢ്ര", "ണ്ട്ര", "ത്ര", "ത്ത്ര", "ത്സ്ര",
                     "ദ്ര", "ധ്ര", "ന്ത്ര", "ന്ദ്ര", "ന്ധ്ര",
                     "പ്ര", "ഫ്ര", "ബ്ര", "ഭ്ര", "മ്ര", "മ്പ്ര",
                     "വ്ര", "ശ്ര", "സ്ര", "ഹ്ര", "ഷ്ര", "റ്റ്ര"]

    ML_LA_CONJUNCTS: ["ക്ല", "ഗ്ല", "ത്ല", "പ്ല", "ഫ്ല", "ബ്ല", "മ്ല", "വ്ല", "സ്ല", "ശ്ല", "ഹ്ല"]
    ML_TOP_MARKS: ["ൎ", "ഀ", "഻"]
    ML_BOTTOM_MARKS: [ "ൢ", "ൣ"]

  # Kern pairs
  kern:
    latin: # script
      - ["@UC_RIGHT_ROUND", "@UC_LEFT_SLANT", -50]
      - ["@UC_RIGHT_ROUND", "@LC_LEFT_ROUND", -20]
      - ["@LC_RIGHT_SLANT", "@LC_LEFT_ROUND", -20]
      - ["@UC_RIGHT_SLANT", "@LC_LEFT_ROUND", -100]
      - ["@UC_RIGHT_SLANT", "@UC_LEFT_ROUND", -50]
      - ["@UC_RIGHT_MOUTH", "@LC_LEFT_SLANT", -50]
      - ["@UC_RIGHT_MOUTH", "@LC_LEFT_ROUND", -50]
      - ["@LC_RIGHT_MOUTHS", "@LC_LEFT_ROUND", -20]
      - ["@LC_RIGHT_MOUTHS", "@LC_LEFT_SLANT", -20]
      - ["@LC_BOTTOM_GAP", "@LC_LEFT_LEG", -50]
      - ["A", ["V", "Y", "T", "v"], -80 ]
      - ["Y", ["A"], -80 ]
    malayalam:
      - ['്',"@QUOTES", 100 ]
      - ['്',"@PARANTHESIS", 100 ]
      - ['്',"!", 100 ]
      - [['ഷ','ക്ഷ'],"സ", -80 ]
      - [['ആ',"ക", "ഷ", 'ക്ഷ', "ദ"],["ന", "ൻ", "നു", "ന്റ", "നൂ"], -50 ]
      - [['പ',"പു", 'പൂ', "വ", "വു", "വൂ"],["ന", "ൻ", "നു", "ന്റ", "നൂ"], -30 ]
      - [['പ',"പു", 'പൂ', "വ", "വു", "വൂ","യ", "യു", "യൂ"],['പ',"പു", 'പൂ', "വ", "വു", "വൂ","യ", "യു", "യൂ"], -30 ]
      - ['മൂ',"സ", -20 ]
      - ['ല',"സ", -20 ]
      - [['ത', 'ന', 'നു', 'ന്ന'],"ം", -30 ]
      - [['സ', 'ഗ'],"ം", -20 ]
      - [ "ം", ['ന', 'നു', 'നൂ', 'സ','സു', 'സൂ'], -30 ]
      - [['ത', 'സ', 'ന', 'നു', 'ന്ന'],["ക","കു","കൂ","കൃ"], -30 ]
      - [['ന്റ', 'ൻ്റ'], "്", 40 ]
  calts:
    malayalam:
      - ['ന', "ി", 'wrap' ]
      - ['ന്റ', "ി", 'narrow' ]
      - ['ന്റ', "ീ", 'narrow' ]

