name: Nupuram
styles: [
  "Regular",
  "Black",
  "Bold",
  "Thin",
  "Light",
  "Display",
  "Slanted",
  "Slanted-Thin",
  "Condensed",
  "Expanded",
  "ExtraSoft",
  "Sharp",
  "Calligraphy",
  "Sans",
  "Outline",
  "Shadow",
  "Arrows",
  "Dots"
]
version: 1.0
source: https://gitlab.com/smc/fonts/nupuram
author:
  name: Santhosh Thottingal
  email: santhosh.thottingal@gmail.com
  url: https://thottingal.in
license:
  text: "This Font Software is licensed under the SIL Open Font License, Version 1.1. This licens is available with a FAQ at: https://scripts.sil.org/OFL"
  url: https://scripts.sil.org/OFL
manufacturer:
  name: SMC
  url: https://smc.org.in
sources: sources
build: fonts
proofs: proofs
tests: tests
glyphs:
  classes:
    LC_ALL: abcdefghijklmnopqrstuvwxyz
    UC_ALL: ABCDEFGHIJKLMNOPQRSTUVWXYZ
    LATIN_EXTRA: ÁǼÂÄÀĀÅÃĆČÇĈĊĎÉĚÊËĖÈĒĜĠĤÍÎÏÌĪĨŃŇÑÓÔÖÒŌÕŔŘŚŠŞŜÚǓÛÜÙŪŮŨŴÝŶŽŻáǽâäàāåãćčçĉċéěêëėèēĝġĥíîïìīĩńňñóǒôöòōõŕřśšşŝúǔûüùūůũŵýŷÿźžż
    LATIN_LIGATURES:  ["ff"] # [ "ff", "ft", "tt", "ffi", "ff", "ee", "th", "ft", "fi", "tt"]
    LC_LEFT_ROUND: ["e", "ee", "c", "a", "d", "o", "q", "g"]
    LC_RIGHT_ROUND: bop
    UC_LEFT_ROUND: OQ
    UC_RIGHT_ROUND: OQDP
    UC_RIGHT_MOUTH: K
    LC_RIGHT_SLANT: ["v", "f", "ff", "k"]
    LC_LEFT_SLANT: ["v"]
    UC_LEFT_SLANT: ["A", "V", "Y", "T"]
    UC_RIGHT_SLANT: TYV
    UC_RIGHT_LEG: ["L"]
    UC_RIGHT_ARM: ["T"]
    LC_RIGHT_ARM: rf
    UC_LEFT_LEG: ["J"]
    LC_LEFT_LEG: ["j"]
    LC_RIGHT_LEG: ["t"]
    LC_RIGHT_MOUTHS: amd
    LC_BOTTOM_GAP: abcdefhiklmnopqrstuvwxz
    QUOTES: ["'","\"","‘","’","“","”"]
    PARANTHESIS: "()"
    ML_CONSONANTS: കഖഗഘങചഛജഝഞടഠഡഢണതഥദധനപഫബഭമയരലവറശഷസഹളഴ
    ML_VOWEL_SIGNS: ['ാ', 'ി','ീ', "ു", "ൂ", "ൃ", "ൄ", "ൢ", "ൣ", "െ", "േ", "ൈ", "ൊ", "ോ","ൌ", "ൗ"]
    ML_VOWEL_SIGNS_CONJOINING: ["ു", "ൂ", "ൃ", "ൄ", "ൢ", "ൣ"]
    ML_I_SIGNS: ['ി','ീ']
    ML_CONS_CONJUNCTS: ["ക്ക", "ക്ഷ", "ഗ്ഗ", "ഗ്ദ", "ഗ്ദ്ധ", "ഗ്ന", "ഗ്മ", "ങ്ങ", "ക്ത", "ങ്ക",
                     "ച്ച", "ച്ഛ", "ജ്ജ", "ഞ്ച", "ഞ്ജ", "ജ്ഞ", "ഞ്ഞ",
                     "ട്ട", "ണ്ണ", "ണ്ഡ", "ണ്ട", "ണ്മ",
                     "ത്ത", "ത്ഥ", "ത്ന", "ത്ഭ", "ദ്ദ", "ദ്ധ", "ന്ന", "ത്സ", "ത്മ", "ന്ത", "ന്ഥ", "ന്ദ", "ന്ധ", "ന്മ", "ന്റ", "ൻ്റ",
                     "പ്പ", "പ്ഫ", "ബ്ബ", "മ്മ", "മ്പ",
                     "യ്യ", "ല്ല", "ല്പ", "വ്വ",
                     "ശ്ച", "സ്സ", "സ്റ്റ", "സ്ഥ", "ശ്ശ", "ഷ്ട", "ഷ്പ","ഹ്ന", "ഹ്മ", "ള്ള", "റ്റ"]
    ML_REPH_CONJUNCTS: ["ക്ര", "ക്ക്ര", "ക്ത്ര", "ഗ്ര", "ഘ്ര", "ങ്ക്ര",
                     "ച്ര", "ജ്ര", "ട്ര", "ഡ്ര", "ഢ്ര", "ണ്ട്ര", "ത്ര", "ത്ത്ര", "ത്സ്ര",
                     "ദ്ര", "ധ്ര", "ന്ത്ര", "ന്ദ്ര", "ന്ധ്ര",
                     "പ്ര", "ഫ്ര", "ബ്ര", "ഭ്ര", "മ്ര", "മ്പ്ര",
                     "വ്ര", "ശ്ര", "സ്ര", "ഹ്ര", "ഷ്ര", "റ്റ്ര"]
    ML_PREVENT_CONJUNCTS: ["ഗ്ഗു", "ഗ്ഗൂ", "ത്ഭൂ", "ല്പു", "ല്പൂ", "ഷ്പു","ഷ്പൂ"]
    ML_LA_CONJUNCTS: ["ക്ല", "ഗ്ല", "ത്ല", "പ്ല", "ഫ്ല", "ബ്ല", "മ്ല", "വ്ല", "സ്ല", "ശ്ല", "ഹ്ല"]
    ML_TOP_MARKS: ["ൎ", "ഀ"]
    ML_BOTTOM_MARKS: [ "ൢ", "ൣ"]

  # Kern pairs
  kern:
    latin: # script
      - ["@UC_RIGHT_ROUND", "@UC_LEFT_SLANT", -50]
      - ["@UC_RIGHT_ROUND", "@LC_LEFT_ROUND", -20]
      - ["@LC_RIGHT_SLANT", "@LC_LEFT_ROUND", -20]
      - ["@UC_RIGHT_SLANT", "@LC_LEFT_ROUND", -100]
      - ["@UC_RIGHT_SLANT", "@UC_LEFT_ROUND", -50]
      - ["@UC_RIGHT_MOUTH", "@LC_LEFT_SLANT", -50]
      - ["@UC_RIGHT_MOUTH", "@LC_LEFT_ROUND", -50]
      - ["@UC_RIGHT_LEG", "@UC_RIGHT_SLANT", -80]
      - ["@UC_RIGHT_LEG", "@LC_LEFT_SLANT", -80]
      - ["@LC_RIGHT_MOUTHS", "@LC_LEFT_ROUND", -20]
      - ["@LC_RIGHT_MOUTHS", "@LC_LEFT_SLANT", -20]
      - ["@LC_RIGHT_ARM", "@LC_LEFT_ROUND", -80]
      - ["@LC_BOTTOM_GAP", "@LC_LEFT_LEG", -50]
      - ["A", ["V", "Y", "T", "v"], -80 ]
      - ["Y", ["A"], -80 ]
      - ["L", ["V"], -80 ]
    malayalam:
      - ['്',"@QUOTES", 100 ]
      - ['്',"@PARANTHESIS", 100 ]
      - ['്',"!", 100 ]
      - [['ഷ','ക്ഷ'],"സ", -80 ]
      - [['ആ',"ക", "ഷ", 'ക്ഷ', "ദ"],["ന", "ൻ", "നു", "ന്റ", "നൂ"], -50 ]
      - [['പ',"പു", 'പൂ', "വ", "വു", "വൂ"],["ന", "ൻ", "നു", "ന്റ", "നൂ"], -30 ]
      - [['പ',"പു", 'പൂ', "വ", "വു", "വൂ","യ", "യു", "യൂ"],['പ',"പു", 'പൂ', "വ", "വു", "വൂ","യ", "യു", "യൂ"], -30 ]
      - ['മൂ',"സ", -20 ]
      - ['ല',"സ", -20 ]
      - [['ത', 'ന', 'നു', 'ന്ന'],"ം", -30 ]
      - [['സ', 'ഗ'],"ം", -20 ]
      - [ "ം", ['ന', 'നു', 'നൂ', 'സ','സു', 'സൂ'], -30 ]
      - [['ത', 'സ', 'ന', 'നു', 'ന്ന'],["ക","കു","കൂ","കൃ"], -30 ]
      - [['ന്റ', 'ൻ്റ'], "്", 40 ]
  calts:
    malayalam:
      - ['ന', "ി", 'wrap' ]
colorfonts:
  fonts/ufo/Nupuram-Shadow-Color.ufo:
    layers:
      "public.default":
        "source": "fonts/ufo/Nupuram-Display.ufo"
        "order": 1  # Foreground layer
      "shadow":
        "source": "fonts/ufo/Nupuram-Shadow.ufo"
        "order": 0  # background layer
    pallettes:
      - ["#E65100", "#FFCC80", "#FF9800"] # Orange
      - ["#212121", "#EEEEEE", "#9E9E9E"] # Gray
      - ["#263238", "#B0BEC5", "#607D8B"] # Blue Gray
      - ["#F57F17", "#FFF59D", "#FFEB3B"] # Yellow
      - ["#1B5E20", "#A5D6A7", "#4CAF50"] # Green
      - ["#01579B", "#81D4FA", "#03A9F4"] # Light Blue
      - ["#0D47A1", "#90CAF9", "#2196F3"] # Blue
      - ["#B71C1C", "#EF9A9A", "#F44336"] # Red
      - ["#4A148C", "#CE93D8", "#9C27B0"] # Purple
      - ["#004D40", "#80CBC4", "#009688"] # Teal
      - ["#3E2723", "#BCAAA4", "#795548"] # Brown
      - ["#880E4F", "#F48FB1", "#E91E63"] # Pink
      - ["#311B92", "#B39DDB", "#673AB7"] # Deep Purple
      - ["#1A237E", "#9FA8DA", "#3F51B5"] # Indigo
      - ["#006064", "#80DEEA", "#00BCD4"] # Cyan
      - ["#33691E", "#C5E1A5", "#8BC34A"] # Light Green
      - ["#827717", "#E6EE9C", "#CDDC39"] # Lime
      - ["#FF6F00", "#FFE082", "#FFC107"] # Amber
      - ["#BF360C", "#FFAB91", "#FF5722"] # Deep Orange
  fonts/ufo/Nupuram-Arrows-Color.ufo:
    layers:
      "public.default":
        "source": "fonts/ufo/Nupuram-Arrows.ufo"
        "order": 1  # Foreground layer
      "shadow":
        "source": "fonts/ufo/Nupuram-Regular.ufo"
        "order": 0  # background layer
    pallettes:
      - ["#E65100", "#FFCC80"] # Orange
      - ["#212121", "#EEEEEE"] # Gray
      - ["#263238", "#B0BEC5"] # Blue Gray
      - ["#F57F17", "#FFF59D"] # Yellow
      - ["#1B5E20", "#A5D6A7"] # Green
      - ["#01579B", "#81D4FA"] # Light Blue
      - ["#0D47A1", "#90CAF9"] # Blue
      - ["#B71C1C", "#EF9A9A"] # Red
      - ["#4A148C", "#CE93D8"] # Purple
      - ["#004D40", "#80CBC4"] # Teal
      - ["#3E2723", "#BCAAA4"] # Brown
      - ["#880E4F", "#F48FB1"] # Pink
      - ["#311B92", "#B39DDB"] # Deep Purple
      - ["#1A237E", "#9FA8DA"] # Indigo
      - ["#006064", "#80DEEA"] # Cyan
      - ["#33691E", "#C5E1A5"] # Light Green
      - ["#827717", "#E6EE9C"] # Lime
      - ["#FF6F00", "#FFE082"] # Amber
      - ["#BF360C", "#FFAB91"] # Deep Orange
