name: Seventy
style: Regular
version: 0.1
source: https://gitlab.com/smc/fonts/seventy
design: sources/design/Regular
author:
  name: Santhosh Thottingal
  email: santhosh.thottingal@gmail.com
  url: https://thottingal.in
license:
  test: "This Font Software is licensed under the SIL Open Font License, Version 1.1. This licens is available with a FAQ at: https://scripts.sil.org/OFL"
  url: https://scripts.sil.org/OFL
manufacturer:
  name: SMC
  url: https://smc.org.in
