font:
    transform: 1 0 0 -1 0 0
    name: Seventy Regular
    ufo: sources/Seventy-Regular.ufo
    version: 2 # UFO version
svgs:
    exclamationmark:
        unicode: '0021'
        glyph_name: exclam
    questionmark:
        unicode: 003F
        glyph_name: question
    hash:
        unicode: '0023'
        glyph_name: numbersign
    multiplicationsign:
        unicode: 00D7
        glyph_name: multiply
    dollar:
        unicode: '0024'
        glyph_name: dollar
    comma:
        unicode: 002C
        glyph_name: comma
    ampersand:
        unicode: '0026'
        glyph_name: ampersand
    quotesingle:
        unicode: '0027'
        glyph_name: quotesingle
    parenthesisleft:
        unicode: '0028'
        glyph_name: parenleft
    equalsign:
        unicode: 003D
        glyph_name: equal
    plus:
        unicode: 002B
        glyph_name: plus
    slash:
        unicode: 002F
        glyph_name: slash
    squarebracketleft:
        unicode: 005B
        glyph_name: bracketleft
    atsign:
        unicode: '0040'
        glyph_name: at
    A:
        unicode: '0041'
        glyph_name: A
    a:
        unicode: '0061'
        glyph_name: a
    acute:
        unicode: '00B4'
        glyph_name: acute
    B:
        unicode: '0042'
        glyph_name: B
    b:
        unicode: '0062'
        glyph_name: b
    c:
        unicode: '0063'
        glyph_name: c
    C:
        unicode: '0043'
        glyph_name: C
    d:
        unicode: '0064'
        glyph_name: d
    D:
        unicode: '0044'
        glyph_name: D
    e:
        unicode: '0065'
        glyph_name: e
    E:
        unicode: '0045'
        glyph_name: E
    F:
        unicode: '0046'
        glyph_name: F
    f:
        unicode: '0066'
        glyph_name: f
    g:
        unicode: '0067'
        glyph_name: g
    G:
        unicode: '0047'
        glyph_name: G
    H:
        unicode: '0048'
        glyph_name: H
    h:
        unicode: '0068'
        glyph_name: h
    I:
        unicode: '0049'
        glyph_name: I
    i:
        unicode: '0069'
        glyph_name: i
    J:
        unicode: 004A
        glyph_name: J
    j:
        unicode: 006A
        glyph_name: j
    K:
        unicode: 004B
        glyph_name: K
    k:
        unicode: 006B
        glyph_name: k
    L:
        unicode: 004C
        glyph_name: L
    l:
        unicode: 006C
        glyph_name: l
    M:
        unicode: 004D
        glyph_name: M
    m:
        unicode: 006D
        glyph_name: m
    N:
        unicode: 004E
        glyph_name: N
    n:
        unicode: 006E
        glyph_name: n
    O:
        unicode: 004F
        glyph_name: O
    o:
        unicode: 006F
        glyph_name: o
    P:
        unicode: '0050'
        glyph_name: P
    p:
        unicode: '0070'
        glyph_name: p
    Q:
        unicode: '0051'
        glyph_name: Q
    q:
        unicode: '0071'
        glyph_name: q
    R:
        unicode: '0052'
        glyph_name: R
    r:
        unicode: '0072'
        glyph_name: r
    s:
        unicode: '0073'
        glyph_name: s
    S:
        unicode: '0053'
        glyph_name: S
    T:
        unicode: '0054'
        glyph_name: T
    t:
        unicode: '0074'
        glyph_name: t
    u:
        unicode: '0075'
        glyph_name: u
    U:
        unicode: '0055'
        glyph_name: U
    V:
        unicode: '0056'
        glyph_name: V
    v:
        unicode: '0076'
        glyph_name: v
    w:
        unicode: '0077'
        glyph_name: w
    W:
        unicode: '0057'
        glyph_name: W
    X:
        unicode: '0058'
        glyph_name: X
    x:
        unicode: '0078'
        glyph_name: x
    Y:
        unicode: '0059'
        glyph_name: Y
    y:
        unicode: '0079'
        glyph_name: y
    z:
        unicode: '007A'
        glyph_name: z
    Z:
        unicode: '005A'
        glyph_name: Z
    braceleft:
        unicode: '007B'
        glyph_name: braceleft
    bar:
        unicode: 007C
        glyph_name: bar
    ം:
        unicode: 0D02
        glyph_name: anuswara
    ഃ:
        unicode: 0D03
        glyph_name: visarga
    Dot_Reph:
        unicode: 0D4E
        glyph_name: dotreph
    അ:
        unicode: 0D05
        glyph_name: ml_a
    ആ:
        unicode: 0D06
        glyph_name: ml_aa
    ഇ:
        unicode: 0D07
        glyph_name: ml_i
    ഉ:
        unicode: 0D09
        glyph_name: ml_u
    ഋ:
        unicode: 0D0B
        glyph_name: ml_r
    ൠ:
        unicode: 0D60
        glyph_name: ml_rr
    ഌ:
        unicode: 0D0C
        glyph_name: ml_l
    ൡ:
        unicode: 0D61
        glyph_name: ml_ll
    എ:
        unicode: 0D0E
        glyph_name: ml_e
    ഏ:
        unicode: 0D0F
        glyph_name: ml_ee
    ഒ:
        unicode: 0D12
        glyph_name: ml_o
    ൿ:
        unicode: 0D7F
        glyph_name: k1cil
    ക:
        unicode: 0D15
        glyph_name: k1
    കു:
        glyph_name: k1u1
    കൂ:
        glyph_name: k1u2
    കൃ:
        glyph_name: k1r1
    കൃൃ:
        glyph_name: k1r2
    ക്ക:
        glyph_name: k1k1
    ക്കു:
        glyph_name: k1k1u1
    ക്കൂ:
        glyph_name: k1k1u2
    ക്കൃ:
        glyph_name: k1k1r1
    ക്ക്ര:
        glyph_name: k1k1r3
    ക്ത:
        glyph_name: k1th1
    ക്തു:
        glyph_name: k1th1u1
    ക്തൂ:
        glyph_name: k1th1u2
    ക്തൃ:
        glyph_name: k1th1r1
    ക്തൃൃ:
        glyph_name: k1th1r2
    ക്ത്ര:
        glyph_name: k1th1r3
    ക്ര:
        glyph_name: k1r3
    ക്ഷ:
        glyph_name: k1sh
    ഖ:
        unicode: 0D16
        glyph_name: k2
    ഖ്ര:
        glyph_name: k2r3
    ഗ:
        unicode: 0D17
        glyph_name: k3
    ഗു:
        glyph_name: k3u1
    ഗൂ:
        glyph_name: k3u2
    ഗൃ:
        glyph_name: k3r1
    ഗ്ഘ:
        glyph_name: k3k4
    ഗ്ദ:
        glyph_name: k3th3
    ഗ്ദൃ:
        glyph_name: k3th3r1
    ഗ്ദ്ധ:
        glyph_name: k3th3th4
    ഗ്ദ്ധൃ:
        glyph_name: k3th3th4r1
    ഗ്ദ്ധ്ര:
        glyph_name: k3th3th4r3
    ഗ്ഗ:
        glyph_name: k3k3
    ഗ്ന:
        glyph_name: k3n1
    ഗ്നു:
        glyph_name: k3n1u1
    ഗ്നൂ:
        glyph_name: k3n1u2
    ഗ്മ:
        glyph_name: k3m1
    ഗ്ര:
        glyph_name: k3r3
    ഘ:
        unicode: 0D18
        glyph_name: k4
    ഘ്ര:
        glyph_name: k4r3
    ങ:
        unicode: 0D19
        glyph_name: ng
    ങ്ക:
        glyph_name: ngk1
    ങ്കു:
        glyph_name: ngk1u1
    ങ്കൂ:
        glyph_name: ngk1u2
    ങ്കൃ:
        glyph_name: ngk1r1
    ങ്കൃൃ:
        glyph_name: ngk1r2
    ങ്ക്ര:
        glyph_name: ngk1r3
    ങ്ങ:
        glyph_name: ngng
    ച:
        unicode: 0D1A
        glyph_name: ch1
    ച്ച:
        glyph_name: ch1ch1
    ഛ:
        unicode: 0D1B
        glyph_name: ch2
    ച്ഛ:
        glyph_name: ch1ch2
    ഛു:
        glyph_name: ch2u1
    ഛൂ:
        glyph_name: ch2u2
    ഛൃ:
        glyph_name: ch2r1
    ഛ്ര:
        glyph_name: ch2r3
    ജ:
        unicode: 0D1C
        glyph_name: ch3
    ജു:
        glyph_name: ch3u1
    ജൂ:
        glyph_name: ch3u2
    ജൃ:
        glyph_name: ch3r1
    ജ്ജ:
        glyph_name: ch3ch3
    ജ്ജു:
        glyph_name: ch3ch3u1
    ജ്ജൂ:
        glyph_name: ch3ch3u2
    ജ്ജൃ:
        glyph_name: ch3ch3r1
    ജ്ഞ:
        glyph_name: ch3nj
    ജ്ര:
        glyph_name: ch3r3
    ഝ:
        unicode: 0D1D
        glyph_name: ch4
    ഝൃ:
        glyph_name: ch4r1
    ഝൃൃ:
        glyph_name: ch4r2
    ഝ്ര:
        glyph_name: ch4r3
    ഞ:
        unicode: 0D1E
        glyph_name: nj
    ഞ്ച:
        glyph_name: njch1
    ഞ്ഛ:
        glyph_name: njch2
    ഞ്ഛു:
        glyph_name: njch2u1
    ഞ്ഛൂ:
        glyph_name: njch2u2
    ഞ്ഛൃ:
        glyph_name: njch2r1
    ഞ്ജ:
        glyph_name: njch3
    ഞ്ജു:
        glyph_name: njch3u1
    ഞ്ജൂ:
        glyph_name: njch3u2
    ഞ്ഞ:
        glyph_name: njnj
    ഞ്ഞു:
        glyph_name: njnju1
    ഞ്ഞൂ:
        glyph_name: njnju2
    ട:
        unicode: 0D1F
        glyph_name: t1
    ടൃ:
        glyph_name: t1r1
    ടൃൃ:
        glyph_name: t1r2
    ട്ട:
        glyph_name: t1t1
    ട്ര:
        glyph_name: t1r3
    ഠ:
        unicode: 0D20
        glyph_name: t2
    ഡ:
        unicode: 0D21
        glyph_name: t3
    ഡൃ:
        glyph_name: t3r1
    ഡ്ര:
        glyph_name: t3r3
    ഢ:
        unicode: 0D22
        glyph_name: t4
    ഢൃ:
        glyph_name: t4r1
    ഢ്ര:
        glyph_name: t4r3
    ൺ:
        unicode: 0D7A
        glyph_name: nhcil
    ണ:
        unicode: 0D23
        glyph_name: nh
    ണ്ണ:
        unicode: 0D23
        glyph_name: nhnh
    ണ്ണു:
        glyph_name: nhnhu1
    ണ്ണൂ:
        glyph_name: nhnhu2
    ണു:
        glyph_name: nhu1
    ണൂ:
        glyph_name: nhu2
    ണ്ട:
        glyph_name: nht1
    ണ്ട്ര:
        glyph_name: nht1r3
    ണ്ഡ:
        glyph_name: nht3
    ണ്ഡൃ:
        glyph_name: nht3r1
    ണ്ഡ്ര:
        glyph_name: nht3r3
    ണ്ഢ:
        glyph_name: nht4
    ണ്ഢൃ:
        glyph_name: nht4r1
    ണ്മ:
        glyph_name: nhm1
    ത:
        unicode: 0D24
        glyph_name: th1
    തു:
        glyph_name: th1u1
    തൂ:
        glyph_name: th1u2
    തൃ:
        glyph_name: th1r1
    ത്ത:
        glyph_name: th1th1
    ത്തു:
        glyph_name: th1th1u1
    ത്തൂ:
        glyph_name: th1th1u2
    ത്തൃ:
        glyph_name: th1th1r1
    ത്തൃൃ:
        glyph_name: th1th1r2
    ത്ത്ര:
        glyph_name: th1th1r3
    ത്ഥ:
        glyph_name: th1th2
    ത്ന:
        glyph_name: th1n1
    ത്ഭ:
        glyph_name: th1p4
    ത്ഭു:
        glyph_name: th1p4u1
    ത്ഭൂ:
        glyph_name: th1p4u2
    ത്ഭൃ:
        glyph_name: th1p4r1
    ത്മ:
        glyph_name: th1m1
    ത്ര:
        glyph_name: th1r3
    ത്സ:
        glyph_name: th1s1
    ത്സൃ:
        glyph_name: th1s1r1
    ത്സൃൃ:
        glyph_name: th1s1r2
    ത്സ്ര:
        glyph_name: th1s1r3
    ഥ:
        unicode: 0D25
        glyph_name: th2
    ഥ്ര:
        glyph_name: th2r3
    ദ:
        unicode: 0D26
        glyph_name: th3
    ധ:
        unicode: 0D27
        glyph_name: th4
    ദൃ:
        glyph_name: th3r1
    ദൃൃ:
        glyph_name: th3r2
    ദ്ദ:
        glyph_name: th3th3
    ദ്ധ:
        glyph_name: th3th4
    ദ്ധൃ:
        glyph_name: th3th4r1
    ദ്ധൃൃ:
        glyph_name: th3th4r2
    ദ്ധ്ര:
        glyph_name: th3th4r3
    ദ്ര:
        glyph_name: th3r3
    ധൃ:
        glyph_name: th4r1
    ധൃൃ:
        glyph_name: th4r2
    ധ്ര:
        glyph_name: th4r3
    ൻ:
        unicode: 0D7B
        glyph_name: n1cil
    ന:
        unicode: 0D28
        glyph_name: n1
    ഩ:
        unicode: 0D29
        glyph_name: n2
    നു:
        glyph_name: n1u1
    നൂ:
        glyph_name: n1u2
    നൃ:
        glyph_name: n1r1
    നൃൃ:
        glyph_name: n1r2
    ന്ത:
        glyph_name: n1th1
    ന്തു:
        glyph_name: n1th1u1
    ന്തൂ:
        glyph_name: n1th1u2
    ന്തൃ:
        glyph_name: n1th1r1
    ന്ത്ര:
        glyph_name: n1th1r3
    ന്ഥ:
        glyph_name: n1th2
    ന്ദ:
        glyph_name: n1th3
    ന്ദൃ:
        glyph_name: n1th3r1
    ന്ദൃൃ:
        glyph_name: n1th3r2
    ന്ദ്ര:
        glyph_name: n1th3r3
    ന്ധ:
        glyph_name: n1th4
    ന്ധ്ര:
        glyph_name: n1th4r3
    ന്ന:
        glyph_name: n1n1
    ന്നു:
        glyph_name: n1n1u1
    ന്നൂ:
        glyph_name: n1n1u2
    ന്നൃ:
        glyph_name: n1n1r1
    ന്നൃൃ:
        glyph_name: n1n1r2
    ന്ന്ര:
        glyph_name: n1n1r3
    ന്മ:
        glyph_name: n1m1
    ന്റ:
        glyph_name: n1rh
    പ:
        unicode: 0D2A
        glyph_name: p1
    പ്പ:
        glyph_name: p1p1
    പ്ഫ:
        glyph_name: p1p2
    പ്ര:
        glyph_name: p1r3
    ഫ:
        unicode: 0D2B
        glyph_name: p2
    ഫ്ര:
        glyph_name: p2r3
    ബ:
        unicode: 0D2C
        glyph_name: p3
    ബ്ര:
        glyph_name: p3r3
    ഭ:
        unicode: 0D2D
        glyph_name: p4
    ഭു:
        glyph_name: p4u1
    ഭൂ:
        glyph_name: p4u2
    ഭൃ:
        glyph_name: p4r1
    ഭൃൃ:
        glyph_name: p4r2
    ഭ്ര:
        glyph_name: p4r3
    ൔ:
        unicode: '0D54'
        glyph_name: m1cil
    മ:
        unicode: 0D2E
        glyph_name: m1
    മൃ:
        glyph_name: m1r1
    മ്പ:
        glyph_name: m1p1
    മ്പ്ര:
        glyph_name: m1p1r3
    മ്ര:
        glyph_name: m1r3
    മ്മ:
        glyph_name: m1m1
    ൕ:
        unicode: 0D55
        glyph_name: y1cil
    യ:
        unicode: 0D2F
        glyph_name: y1
    ർ:
        unicode: 0D7C
        glyph_name: r3cil
    ര:
        unicode: 0D30
        glyph_name: r3
    രു:
        glyph_name: r3u1
    രൂ:
        glyph_name: r3u2
    രൃ:
        glyph_name: r3r1
    ൽ:
        unicode: 0D7D
        glyph_name: l3cil
    ല:
        unicode: 0D32
        glyph_name: l3
    ല്പ:
        glyph_name: l3p1
    വ:
        unicode: 0D35
        glyph_name: v1
    വ്ര:
        glyph_name: v1r3
    ശ:
        unicode: 0D36
        glyph_name: z1
    ശു:
        glyph_name: z1u1
    ശൂ:
        glyph_name: z1u2
    ശൃ:
        glyph_name: z1r1
    ശ്ശ:
        glyph_name: z1z1
    ശ്ച:
        glyph_name: z1ch1
    ശ്ര:
        glyph_name: z1r3
    ഷ:
        unicode: 0D37
        glyph_name: sh
    ഷ്ര:
        glyph_name: shr3
    സ:
        unicode: 0D38
        glyph_name: s1
    സൃ:
        glyph_name: s1r1
    സൃൃ:
        glyph_name: s1r2
    സ്ഥ:
        glyph_name: s1th2
    സ്പ:
        glyph_name: s1p1
    സ്സ:
        glyph_name: s1s1
    സ്ത്ര:
        glyph_name: s1th1r3
    സ്ര:
        glyph_name: s1r3
    ഹ:
        unicode: 0D39
        glyph_name: h1
    ഹു:
        glyph_name: h1u1
    ഹൂ:
        glyph_name: h1u2
    ഹൃ:
        glyph_name: h1r1
    ഹ്ന:
        glyph_name: h1n1
    ഹ്നു:
        glyph_name: h1n1u1
    ഹ്നൂ:
        glyph_name: h1n1u2
    ഹ്മ:
        glyph_name: h1m1
    ഹ്ര:
        glyph_name: h1r3
    ൾ:
        unicode: 0D7E
        glyph_name: lhcil
    ള:
        unicode: 0D33
        glyph_name: lh
    ള്ള:
        glyph_name: lhlh
    ൖ:
        unicode: 0D56
        glyph_name: zhcil
    ഴ:
        unicode: 0D34
        glyph_name: zh
    റ:
        unicode: 0D31
        glyph_name: rh
    റ്റ:
        glyph_name: rhrh
    റ്റ്ര:
        glyph_name: rhrhr3
    ്:
        unicode: 0D4D
        glyph_name: xx
    ്ച:
        glyph_name: va_sign
    ്യ:
        glyph_name: y2
    ്ര:
        glyph_name: r4
    ്ല:
        glyph_name: l4
    ്വ:
        glyph_name: v2
    ാ:
        unicode: 0D3E
        glyph_name: a2
    ി:
        unicode: 0D3F
        glyph_name: i1
    ീ:
        unicode: 0D40
        glyph_name: i2
    ു:
        unicode: 0D41
        glyph_name: u1
    ു_short:
        glyph_name: u_sign_drop
    ു_small:
        glyph_name: u_sign_drop_small
    ൂ:
        unicode: 0D42
        glyph_name: u2
    ൂ_short:
        glyph_name: uu_sign_drop
    ൂ_small:
        glyph_name: uu_sign_drop_small
    െ:
        unicode: 0D46
        glyph_name: e1
    േ:
        unicode: 0D47
        glyph_name: e2
    ൗ:
        unicode: 0D57
        glyph_name: au2
    ൃ_short:
        glyph_name: vocalic_r_sign_drop
    ൃ:
        unicode: 0D43
        glyph_name: r1
    ൄ_short:
        glyph_name: vocalic_rr_sign_drop
    ൄ:
        unicode: 0D44
        glyph_name: r2
    ഌ_small:
        unicode: 0D62
        glyph_name: l1
    ക_small:
        glyph_name: _k1
    കു_small:
        glyph_name: _k1u1
    കൂ_small:
        glyph_name: _k1u2
    കൃ_small:
        glyph_name: _k1r1
    ക്ര_small:
        glyph_name: _k1r3
    ഖ_small:
        glyph_name: _k2
    ഗ_small:
        glyph_name: _k3
    ഗു_small:
        glyph_name: _k3u1
    ഗൂ_small:
        glyph_name: _k3u2
    ഗൃ_small:
        glyph_name: _k3r1
    ഗ്ര_small:
        glyph_name: _k3r3
    ച_small:
        glyph_name: _ch1
    ഛ_small:
        glyph_name: _ch2
    ഛു_small:
        glyph_name: _ch2u1
    ഛൂ_small:
        glyph_name: _ch2u2
    ഛൃ_small:
        glyph_name: _ch2r1
    ഛ്ര_small:
        glyph_name: _ch2r3
    ജ_small:
        glyph_name: _ch3
    ജു_small:
        glyph_name: _ch3u1
    ജൂ_small:
        glyph_name: _ch3u2
    ജൃ_small:
        glyph_name: _ch3r1
    ട_small:
        glyph_name: _t1
    ട്ര_small:
        glyph_name: _t1r3
    ഠ_small:
        glyph_name: _t2
    ഡ_small:
        glyph_name: _t3
    ഢ_small:
        glyph_name: _t4
    ണ_small:
        glyph_name: _nh
    ണു_small:
        glyph_name: _nhu1
    ത_small:
        width: 500
        glyph_name: _th1
    തു_small:
        glyph_name: _th1u1
    തൂ_small:
        glyph_name: _th1u2
    തൃ_small:
        glyph_name: _th1r1
    തൃൃ_small:
        glyph_name: _th1r2
    ത്ത_small:
        glyph_name: _th1th1
    ത്തു_small:
        glyph_name: _th1th1u1
    ത്തൂ_small:
        glyph_name: _th1th1u2
    ത്ര_small:
        width: 865
        glyph_name: _th1r3
    ദ_small:
        width: 275
        glyph_name: _th3
    ദൃ_small:
        glyph_name: _th3r1
    ധ_small:
        glyph_name: _th4
    ധൃ_small:
        glyph_name: _th4r1
    ധൃൃ_small:
        glyph_name: _th4r2
    ന_small:
        glyph_name: _n1
    നു_small:
        glyph_name: _n1u1
    നൂ_small:
        glyph_name: _n1u2
    നൃ_small:
        glyph_name: _n1r1
    ന്ര_small:
        glyph_name: _n1r3
    ന്ന_small:
        glyph_name: _n1n1
    ന്നു_small:
        glyph_name: _n1n1u1
    ന്നൂ_small:
        glyph_name: _n1n1u2
    പ_small:
        glyph_name: _p1
    പ_small_2:
        glyph_name: _p1_
    പ്ര_small:
        glyph_name: _p1r3
    ഫ_samll:
        glyph_name: _p2
    ബ_small:
        glyph_name: _p3
    ഭ_small:
        glyph_name: _p4
    മ_small:
        glyph_name: _m1
    ല_top:
        glyph_name: l3_
    വ_small:
        glyph_name: _v1
    ശ_small:
        glyph_name: _z1
    ശു_small:
        glyph_name: _z1u1
    ശൂ_small:
        glyph_name: _z1u2
    ശൃ_small:
        glyph_name: _z1r1
    ശ്ര_small:
        glyph_name: _z1r3
    സ_small:
        glyph_name: _s1
    സ_top:
        glyph_name: s1_
    സൃ_small:
        glyph_name: _s1r1
    സൃൃ_small:
        glyph_name: _s1r2
    സ്ര_small:
        glyph_name: _s1r3
    ഹ_small:
        glyph_name: _h1
    റ_small:
        glyph_name: _rh
    റ്റ്ര_small:
        glyph_name: _rhrhr3
    ഺ:
        unicode: 0D3A
        glyph_name: rh_half
    ൘:
        unicode: 0D58
        glyph_name: mlarakaani
    ൙:
        unicode: 0D59
        glyph_name: mlaramaa
    ൦:
        unicode: 0D67
        glyph_name: mlzero
    ൧:
        unicode: 0D67
        glyph_name: mlone
    ൨:
        unicode: 0D68
        glyph_name: mltwo
    ൩:
        unicode: 0D69
        glyph_name: mlthree
    ൪:
        unicode: 0D6A
        glyph_name: mlfour
    ൫:
        unicode: 0D6B
        glyph_name: mlfive
    ൬:
        unicode: 0D6C
        glyph_name: mlsix
    ൭:
        unicode: 0D6D
        glyph_name: mlseven
    ൮:
        unicode: 0D6E
        glyph_name: mleight
    ൯:
        unicode: 0D6F
        glyph_name: mlnine
    ൰:
        unicode: 0D70
        glyph_name: mlten
    ൳:
        unicode: 0D73
        glyph_name: kaal
    '0':
        unicode: '0030'
        glyph_name: zero
    '1':
        unicode: '0031'
        glyph_name: one
    '2':
        unicode: '0032'
        glyph_name: two
    '3':
        unicode: '0033'
        glyph_name: three
    '4':
        unicode: '0034'
        glyph_name: four
    '5':
        unicode: '0035'
        glyph_name: five
    '6':
        unicode: '0036'
        glyph_name: six
    '7':
        unicode: '0037'
        glyph_name: seven
    '8':
        unicode: '0038'
        glyph_name: eight
    '9':
        unicode: '0039'
        glyph_name: nine
    bullet:
        unicode: '2022'
        glyph_name: bullet
    ₹:
        unicode: '20B9'
        glyph_name: rupee