% Display font
% This variant has extra thickness for terminals, Letters have more height than regular
% variants.
xheight :=      6u;           % Height of English small letters
mheight :=      7u;           % Height of Malayalam letters
descent :=      2u;           % Descender Height
ascent  :=      9u;           % Ascender Height
Xheight :=      9u;           % Height of English capital letters
xthick  :=      1.25;         % Extra thickness for terminals